// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH4y_JSGRs7GK84uQT_NKWW_zIBCxZuYk',
    appId: '1:209174601158:ios:a2b2fd149a3da7aeb7a6c7',
    messagingSenderId: '209174601158',
    projectId: 'shopsmart-a845d',
    storageBucket: 'shopsmart-a845d.appspot.com',
    iosClientId:
        '209174601158-ijj1jnc472h29nrpv8f1spf321hpr5qh.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH4y_JSGRs7GK84uQT_NKWW_zIBCxZuYk',
    appId: '1:209174601158:ios:a2b2fd149a3da7aeb7a6c7',
    messagingSenderId: '209174601158',
    projectId: 'shopsmart-a845d',
    storageBucket: 'shopsmart-a845d.appspot.com',
    iosClientId:
        '209174601158-ijj1jnc472h29nrpv8f1spf321hpr5qh.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopSmart',
  );
}
